#!/usr/bin/env bash
# Starts the jobs portal.
#
#   ./start.sh                 # normal mode: real .env, real db/app-db.sqlite3
#   ./start.sh --demo          # demo mode: synthetic data, isolated db/demo.sqlite3
#   ./start.sh --demo --reset  # demo mode, wipe and regenerate the demo data
#   ./start.sh --build         # production build + start instead of dev server
#   ./start.sh -p 3000         # override the port (default: 3000, or 3209 for --demo/--build)
#
# Normal mode never touches demo data or generates fake secrets — it expects
# a real .env and a real database, per README.md ("Get a copy from another
# developer rather than generating one").
#
# Demo mode is fully self-contained: it generates its own .env.demo (gitignored,
# fake credentials only) and seeds db/demo.sqlite3 with synthetic applicants via
# scripts/seed-demo.mjs. It never reads or writes the real .env or
# db/app-db.sqlite3, so it's safe to run on a machine that also has real data.
#
# See AGENTS.md: `npm run build` rewrites .next and corrupts a running dev
# server's Turbopack cache. This script defaults to `next dev` for that reason;
# pass --build only when nothing else is serving this project.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

DEMO=false
RESET=false
BUILD=false
PORT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --demo) DEMO=true ;;
    --reset) RESET=true ;;
    --build|--prod) BUILD=true ;;
    -p|--port) PORT="$2"; shift ;;
    -h|--help)
      sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
  shift
done

if [[ "$RESET" == true && "$DEMO" == false ]]; then
  echo "--reset only makes sense with --demo" >&2
  exit 1
fi

if [[ -z "$PORT" ]]; then
  PORT=$([[ "$BUILD" == true || "$DEMO" == true ]] && echo 3209 || echo 3000)
fi

port_in_use() {
  (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null && exec 3<&- 3>&-
}

if port_in_use "$PORT"; then
  echo "✗ Port $PORT is already in use." >&2
  echo "  If that's an existing dev server for this project, stop it first —" >&2
  echo "  running a second one (or a build) alongside it can corrupt its .next cache." >&2
  exit 1
fi

if [[ ! -d node_modules ]]; then
  echo "Installing dependencies..."
  npm install
fi

if [[ "$DEMO" == true ]]; then
  ENV_FILE=".env.demo"
  DB_URL="file:./db/demo.sqlite3"

  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Generating $ENV_FILE (demo-only credentials, never used for real data)..."
    AUTH_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    gen_keypair() { node -e "console.log(Array.from(require('crypto').randomBytes(32)).join(' '))"; }

    cat > "$ENV_FILE" <<EOF
# Generated by start.sh --demo. Fake credentials for demo use only — never
# points at real data and is never used to reach the real AWS submissions
# endpoint. Safe to delete; start.sh --demo regenerates it.
DATABASE_URL="$DB_URL"
AUTH_SECRET="$AUTH_SECRET"
APPS_PUBLIC_HOST="https://demo.invalid"
TRL_PUB="$(gen_keypair)"
TRL_SEC="$(gen_keypair)"
SRM_PUB="$(gen_keypair)"
SRM_SEC="$(gen_keypair)"
SLI_PUB="$(gen_keypair)"
SLI_SEC="$(gen_keypair)"
NFL_PUB="$(gen_keypair)"
NFL_SEC="$(gen_keypair)"
S_PUB="$(gen_keypair)"
S_SEC="$(gen_keypair)"
EOF
  fi

  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
else
  if [[ ! -f .env ]]; then
    echo "✗ No .env file found." >&2
    echo "  Normal mode needs a real one — see 'Getting started' in README.md." >&2
    echo "  For a presentation with synthetic data instead, run: ./start.sh --demo" >&2
    exit 1
  fi
fi

echo "Generating Prisma client..."
npx prisma generate

echo "Applying schema (prisma db push)..."
npx prisma db push

if [[ "$DEMO" == true ]]; then
  if [[ "$RESET" == true ]]; then
    node scripts/seed-demo.mjs --reset
  else
    node scripts/seed-demo.mjs
  fi
fi

if [[ "$BUILD" == true ]]; then
  echo "Building for production..."
  npx next build
  echo "Starting on http://localhost:$PORT ..."
  exec npx next start -p "$PORT"
else
  echo "Starting dev server on http://localhost:$PORT ..."
  exec npx next dev -p "$PORT"
fi
